### ISSUE TITLE
Enable automated Continuous Integration (CI)

### ISSUE THREAD

**Issue by leonardo-brickabode** [Marketing-Automation-Systems/jellyfish#11]
- [x] I have searched the [issues](https://github.com/Marketing-Automation-Systems/jellyfish/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

We should enable an automated Continuous Integration (CI) server to run the tests and other tasks to improve the project's development when we push new code. This will provide more confidence to the contributors developing with the code, if the commit passes all the tests executed by CI, the code is good to go.

How it should work
- Developers check out code into their private workspaces
- When done, commit the changes to the repository
- The CI server monitors the repository and checks out changes when they occur
- The CI server builds the system and runs unit and integration tests
- The CI server informs the team of the successful build
- If the build or tests fail, the CI server alerts the team
- The team fixes the issue at the earliest opportunity
- Continue to continually integrate and test throughout the project

## Examples 🌈

We should consider using the [Github actions](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-continuous-integration) to enable a CI server

## Motivation 🔦

Continuous integration (CI) is a software practice that requires frequently committing code to a shared repository. Committing code more often detects errors sooner and reduces the amount of code a developer needs to debug when finding the source of an error. Frequent code updates also make it easier to merge changes from different members of a software development team. 

By having an automated CI server that checks for new code commits in a repository, the code will be continuously built and tested to make sure that the commit doesn't introduce errors. The tests can include code linters (which check style formatting), security checks, code coverage, functional tests, and other custom checks. This is great for developers, who can spend more time writing code and less time debugging errors or resolving merge conflicts.

**Comment by FredRanieri** [comment]
This issue can be closed due to the result of #13
