### ISSUE TITLE
Add Subscribers Gained and Subscribers Lost on Analytics Database

### ISSUE THREAD

**Issue by FredRanieri** [Marketing-Automation-Systems/jellyfish#9]
- [x] I have searched the [issues](https://github.com/Marketing-Automation-Systems/jellyfish/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

`Subscribers Gained` and `Subscribers Lost` are metrics related to the number of subscribers that a YouTube Channel Gained/Lost from a specific video.

Currently, we are Fetching this information from **YouTube Analytics API**, but we are not using it. 

### References

- [YouTube Analytics API](https://developers.google.com/youtube/analytics)
- Metrics:
   - [Subscribers Gained](https://developers.google.com/youtube/reporting/v1/reports/metrics#subscribers_gained)
   - [Subscribers Lost](https://developers.google.com/youtube/reporting/v1/reports/metrics#subscribers_lost)

## Motivation 🔦

Adding the metrics `Subscribers Gained` and `Subscribers Lost` will make the application database more complete.

**Comment by leonardo-brickabode** [comment]
This issue was migrated from the closed source project, called YEAR-AP, that originated this project. As stated on issue #25, we are going to remove the frontend, application database and transformers from this repository. Therefore, this issue will be closed.
